version: '3.8'

services:
  # Base de Datos con PGVECTOR
  postgres-db:
    # Usamos la imagen oficial que trae pgvector pre-compilado
    image: pgvector/pgvector:pg15
    container_name: projectstalker-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projectstalker_db
    ports:
      - "5432:5432"
    volumes:
      # 1. Persistencia: Para no perder los datos al apagar
      - postgres_data:/var/lib/postgresql/data
      # 2. Inicialización: Inyectamos tu script SQL para que se ejecute al inicio
      - ./docker-data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Interfaz gráfica para ver la BD (Opcional pero recomendada)
  pgadmin:
    image: dpage/pgadmin4
    container_name: projectstalker-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: