services:
  neo4j:
    image: neo4j
    container_name: stalker_intelligence
    ports:
      - "7474:7474" # HTTP Browser
      - "7687:7687" # Bolt (Driver Python)
    environment:
      - NEO4J_AUTH=neo4j/12345678secret
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
      - ./neo4j_import:/var/lib/neo4j/import
    restart: unless-stopped